### PR TITLE
fix: parse title from qMetaDef

### LINKED ISSUE #534: No sheets titles in app object ls functions
Function `app object ls` returns sheets without title.
`App object properties` for a specific sheet returns json with sheet title.

### PR DESCRIPTION
**Pull request by wennmo**
`Title` was never populated when listing objects. This PR changes so we populate `Title` from `qMetaDef/title`.

This closes #534.

### CODE REVIEW

File: internal/entities.go [hunk 1]
```diff
@@ -33,7 +33,9 @@ type (
 	// PropsWithTitle struct
 	PropsWithTitle struct {
 		*enigma.GenericObjectProperties
-		Title string `json:"title"`
+		QMetaDef struct {
```
Comment (glooms) [inline internal/entities.go:36]: Could this be its own struct instead of an anonymous one?
