### PR TITLE
Wait for onConnected event from engine and print event messages if in verbose mode

### LINKED ISSUE #90: Catch no license message on ws
When engine is configuered to run with a license service and the license service isn't working / no licenses left, engine will return on the websocket a message explaining this. 
Catch this error and display in the console. Today we will get: 
`websocket: close 1006 (abnormal closure): unexpected EOF`

### PR DESCRIPTION
**Pull request by FredrikFolkesson**
Wait for `onConnected` event from engine before moving on.

Print session events if in verbose mode

This closes #90

### CODE REVIEW

File: internal/state.go [hunk 1]
```diff
@@ -74,13 +76,12 @@ func PrepareEngineState(ctx context.Context, engine string, appID string, ttl st
...
-				fmt.Println(x.Topic, string(x.Content))
-			}
-		}
-	}()
+	sessionMessages := global.SessionMessageChannel()
+	err := waitForOnConnectedMessage(sessionMessages)
+	if err != nil {
+		FatalError("Failed to connect to engine with error message: ", err)
+	}
+	go printSessionMessagesIfInVerboseMode(sessionMessages)
```
Comment (gabbaxx) [inline internal/state.go]: We are "looping" over the same channel twice. Doesn't this mean that the second loop will never receive the items that the first loop consumed?

File: internal/state.go [hunk 2]
```diff
@@ -131,18 +132,48 @@ func PrepareEngineState(ctx context.Context, engine string, appID string, ttl st
...
+
 	if err != nil {
 		logConnectError(err, engine)
 	}
+	sessionMessages := global.SessionMessageChannel()
+	err = waitForOnConnectedMessage(sessionMessages)
+	if err != nil {
+		FatalError("Failed to connect to engine with error message: ", err)
+	}
+	go printSessionMessagesIfInVerboseMode(sessionMessages)
```
Comment (gabbaxx) [inline internal/state.go]: Same as above

File: internal/state.go (hunk 1 above)
Comment (FredrikFolkesson) [reply internal/state.go]: True, will fix
