### PR TITLE
fix: Add unbuild support for all unicode letters

### LINKED ISSUE #432: Adding recognition of Cyrillic object names to unbuilder.go
The code would look like
var matchAllNonAlphaNumeric = regexp.MustCompile(`[^a-zA-Zа-яА-ЯЁё0-9]+`)
Could anyone give a hand with commiting this to the code?
[unbuilder.go.txt](https://github.com/qlik-oss/corectl/files/3689587/unbuilder.go.txt)

### PR DESCRIPTION
**Pull request by glooms**
Resolve #432

### CODE REVIEW

File: internal/unbuilder.go [hunk 1]
```diff
@@ -37,7 +37,7 @@ type (
 	}
 )
 
-var matchAllNonAlphaNumeric = regexp.MustCompile(`[^a-zA-Z0-9]+`)
+var matchAllNonAlphaNumeric = regexp.MustCompile(`[^\pL\d_-]+`)
```
Comment (wennmo) [inline internal/unbuilder.go]: Can you just add a comment regarding this regexp?
